<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <OutputType>Exe</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>Precursor</RootNamespace>
    <AssemblyName>Precursor</AssemblyName>
    <ApplicationIcon>Precursor.ico</ApplicationIcon>
    <TargetFramework>net8.0-windows</TargetFramework>
    <SatelliteResourceLanguages>none</SatelliteResourceLanguages>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>12</LangVersion>
    <GenerateLaunchSettingsFile>false</GenerateLaunchSettingsFile>
    <Deterministic>false</Deterministic>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <Platforms>x64</Platforms>
    <Configuration>Release</Configuration>
    <Platform>x64</Platform>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Precursor.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
